# Generated by Django 5.2 on 2025-11-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('SENTENCE_MEANING', '문장 의미'), ('SITUATION_TEXT', '상황-텍스트'), ('SITUATION_IMAGE', '상황-이미지')], max_length=32)),
                ('locale', models.CharField(default='ko', max_length=10)),
                ('difficulty', models.CharField(choices=[('EASY', '하'), ('MEDIUM', '중'), ('HARD', '상')], default='EASY', max_length=10)),
                ('prompt_text', models.TextField(blank=True)),
                ('prompt_img', models.URLField(blank=True)),
                ('hint_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['qtype', 'difficulty', 'locale'], name='dotori_quiz_qtype_b478e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=512)),
                ('image_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=256)),
                ('is_correct', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dotori_quizzes.quiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotori_quizzes.option')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotori_quizzes.quiz')),
            ],
        ),
    ]
