# Generated by Django 5.2 on 2025-12-01 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.PositiveIntegerField(help_text='월 정기결제 금액 (KRW)')),
                ('summary_limit_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('image_limit_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('detector_limit_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('point_per_quiz_correct', models.PositiveIntegerField(default=0)),
                ('point_per_roleplay_5min', models.PositiveIntegerField(default=0)),
                ('point_daily_cap', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.PositiveIntegerField(help_text='총 결제 금액 (원가)')),
                ('amount_point_used', models.PositiveIntegerField(default=0)),
                ('amount_paid_cash', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit card'), ('EASY_PAY', 'Easy pay')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('pg_provider', models.CharField(blank=True, max_length=64)),
                ('pg_tid', models.CharField(blank=True, max_length=128)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='dotori_memberships.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('EARN', 'Earn'), ('SPEND', 'Spend')], max_length=8)),
                ('amount', models.PositiveIntegerField(help_text='변동 포인트 (절대값, tx_type 으로 방향 구분)')),
                ('reason', models.CharField(choices=[('QUIZ_CORRECT', 'Quiz correct'), ('ROLEPLAY', 'Roleplay'), ('PURCHASE_DISCOUNT', 'Purchase discount'), ('ADJUST', 'Manual adjust')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='dotori_memberships.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feature_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('IMAGE', 'Image Generation'), ('DETECTOR', 'AI Detector'), ('POINT_EARN', 'Point Earn')], max_length=16)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'feature_type')},
            },
        ),
    ]
