# Generated by Django 5.2 on 2025-12-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotori_memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='pg_provider',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='pg_tid',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='raw_response',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='CARD', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dotori_memberships.membershipplan'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
