# Generated by Django 5.2 on 2025-12-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotori_accounts', '0002_profile_phone_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessible_mode',
            field=models.BooleanField(default=True, help_text='쉬운 모드 / 접근성 모드 (큰 글씨, 단순 UI 등)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', '쉬움'), ('NORMAL', '보통'), ('HARD', '어려움')], default='EASY', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
    ]
