# Generated by Django 5.2 on 2025-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotori_accounts', '0003_profile_accessible_mode_profile_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accessible_mode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notify_push',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notify_sms',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='dotori_acco_email_81606f_idx')],
            },
        ),
    ]
